[features]
seeds = false
skip-lint = false

[programs.localnet]
solora-order-book = "8b5j5Ua8jBDqnCZNB22NJAedd5TBs5NBAjqF65q8BpuS"
solora-pyth-price = "SPPQ71aSCVntCUUWYxpkQa6awxpfgWsuU13H4WTwEAG"
pyth = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --grep ab"
