[features]
seeds = false
skip-lint = false

[programs.localnet]
solora = "14SStXZMvqahGWKeU3699C6of1dcmvvaa3b5ESsvz6U2"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --grep ab"
